### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by KristofferC** [JuliaSparse/MKLSparse.jl#1]
Hello, I am interested in contributing to this.

I have previously done some work that integrates the Pardiso interface in MKL here https://github.com/JuliaSparse/Pardiso.jl. Is that something you plan on adding to this package? In that case I could probably help a bit with that.

Since this package is MKL specific maybe it is better to use the more simple DSS interface in MKL https://software.intel.com/en-us/node/470302 instead of the Pardiso interface?

**Comment by dmbates** [comment]
That would be great, @KristofferC.  I started this with @ViralBShah and @andreasnoack today.  @andreasnoack had written wrappers for the [sdcz]csc[ms][mv] MKL Blas 2 routines (in src/generator.jl) and I have started wrapping them in the src/matmul.jl file.

I would recommend keeping the style of writing similarly named wrappers for the MKL subroutines then writing another set of wrappers that fit into the Julia naming scheme.

**Comment by ViralBShah** [comment]
It does seem to have everything that is MKL sparse specific to be in the same package. Should we merge the Pardiso.jl work in here and have one repo?

**Comment by KristofferC** [comment]
Well, firstly, `Pardiso.jl` does not override Base functions which seems to be the point of this package.

Secondly, it might be worth to wrap the MKL DSS interface instead. This is quite a lot simpler than the Pardiso interface. For users who want the extra capabilities of the Pardiso interface they could just use `Pardiso.jl`
