### ISSUE TITLE
Julia 1.0 Support?

### ISSUE THREAD

**Issue by nrontsis** [JuliaSparse/MKLSparse.jl#15]
Hi, are there any plans to support Julia 1.0?

**Comment by KristofferC** [comment]
Yeah, I will try to get this done at some point.

The MKL Sparse BLAS API we are using seems deprecated (https://software.intel.com/en-us/mkl-developer-reference-fortran-sparse-blas-level-2-and-level-3-routines).

Should probably upgrade to the new one (https://software.intel.com/en-us/mkl-developer-reference-fortran-sparse-blas-level-2-and-level-3-routines).

**Comment by KristofferC** [comment]
I always do this... updated.
