### ISSUE TITLE
Add dependency on MKL_jll.jl

### ISSUE THREAD

**Issue by andreasnoack** [JuliaSparse/MKLSparse.jl#18]
That would make the package work automatically and make it easy to enable CI. MKL.jl overwrites OpenBLAS which currently can cause some issues when using other binary dependencies which require BLAS, e.g. Arpack so we might want to wait a bit. MKL.jl also causes a regression in REPL compile latency but hopefully, I'll be able to fix that soon.

We could probably add MKL.jl as a test dependency here as soon as it has been registered.

**Comment by andreasnoack** [comment]
Well. We probably don't need to MKL.jl to be registered to use it for testing.

**Comment by KristofferC** [comment]
But this package already works automatically (as long as you set the env variables with the `mklvars` script).

**Comment by andreasnoack** [comment]
Yeah. I wasn't precise. I meant without a preinstalled MKL.

**Comment by arnavs** [comment]
Just a question on this issue.

An RA here is working on fleshing out coverage in MKLSparse. The MKL downloads for Mac on Intel's site are broken, so setting the environment variables is impossible. Instead, we decided to install `MKL.jl`, and then nuke the piece of code that manually links to it (i.e., the `__init__().`)

Is this correct? (Basically, if you added `MKL.jl` as a dep, would that init function be irrelevant?)

**Comment by KristofferC** [comment]
Update here: What should be done is to depend on `MKL_jll` and use that (no need to use MKL.jl).

**Comment by ywa136** [comment]
Hi guys, a question.

I'm new to Julia, MKL, and MKLSparse. I'm having trouble getting MKLSparse to work because it could not load the library "libmkl_rt". I understand that you mentioned to depend the package on MKL or MKL_jll. But how that exactly works? More specifically, how do I depend MKLSparse to one of those?

Many thanks!

**Comment by pablosanjose** [comment]
@ywa136 , what you need to do is install the MKL library (from Intel) in your system, and load the env variables before launching Julia (`source /opt/intel/mkl/bin/mklvars.sh intel64 ilp64` or somesuch). What these gentlemen are discussing here is not anything the user needs to do, it is a mechanism to allow, in the future, to download the library automatically so the user doesn't have to. Also, please direct your questions to e.g. discourse.julialang.org, so we can keep github focused on development issues.
