### ISSUE TITLE
Are sparse matrix-matrix multiplications implemented?

### ISSUE THREAD

**Issue by jamblejoe** [JuliaSparse/MKLSparse.jl#27]
Running sparse matrix-dense-vector calculations I can see multi threads being used. I do not see this for sparse matrix-matrix multiplcations. Are they implemented? `@code_lowered` returns the `SparseArray` `mul!` function
```
julia> @code_lowered A*A
CodeInfo(
1 ─ %1 = SparseArrays.spmatmul(A, B)
└──      return %1
)
```

**Comment by KristofferC** [comment]
I don't think MKL has any implementation for that, at least not when this wrapper was written.

**Comment by jamblejoe** [comment]
On the intel website they list routines for matrix-matrix multiplications (https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-c/top/blas-and-sparse-blas-routines/sparse-blas-level-2-and-level-3-routines/sparse-blas-level-2-and-level-3-routines-1.html). I thought they would refer to sparse matrix-matrix multiplications but they are sparse-dense matrix mulitplication routines.
