### ISSUE TITLE
The speed ratio of matrix multiplication using MKLSparse stop to grow while number of of threads >= 8.

### ISSUE THREAD

**Issue by deltaeecs** [JuliaSparse/MKLSparse.jl#29]
In my practice, the speed ratio of sparse matrix multiplication using MKLSparse stop to grow while number of of threads >= 8.
Here is my result

![2022-02-16 093701](https://user-images.githubusercontent.com/48714525/154179674-7a2f7431-5030-4075-9576-f4158d737000.jpg)

System info
```
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cascadelake)
```

**Comment by pablosanjose** [comment]
That's probably a gripe for the MKL library itself, nothing to do with MKLSparse, right?

**Comment by deltaeecs** [comment]
> That's probably a gripe for the MKL library itself, nothing to do with MKLSparse.jl, right?

Yes, I agree now. Maybe CSR format is a better choice.
